/**
 * Generates the reference docs from the source of truth, so they cannot drift:
 *
 *  - docs/COMMANDS.md      from the live command registry (via the test mocks)
 *  - docs/PERMISSIONS.md   from the permission catalogue and default roles
 *  - docs/CONFIGURATION.md from the Config interface and its defaults
 */
import * as esbuild from 'esbuild';
import { mkdtemp, mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const outDir = await mkdtemp(path.join(tmpdir(), 'adm-docs-'));

for (const [name, file] of [['server', 'server.mjs'], ['server-ui', 'server-ui.mjs']]) {
  const dir = path.join(outDir, 'node_modules', '@minecraft', name);
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, 'package.json'), JSON.stringify({ name: `@minecraft/${name}`, type: 'module', main: 'index.mjs' }));
  const target = new URL(`file://${path.join(ROOT, 'test', 'mocks', file)}`).href;
  await writeFile(path.join(dir, 'index.mjs'), `export * from ${JSON.stringify(target)};\n`);
}

const outfile = path.join(outDir, 'docs-entry.mjs');
await esbuild.build({
  stdin: {
    contents: `
      import './src/main';
      import { commands, usageOf } from './src/core/commands';
      export { commands, usageOf };
    `,
    resolveDir: ROOT,
    loader: 'ts',
  },
  outfile,
  bundle: true,
  format: 'esm',
  target: 'es2022',
  platform: 'neutral',
  external: ['@minecraft/server', '@minecraft/server-ui'],
});

// Silence the addon's own startup logging while the bundle initialises.
const realConsole = globalThis.console;
globalThis.console = { ...realConsole, log: () => {}, warn: () => {} };
const { commands, usageOf } = await import(outfile);
globalThis.console = realConsole;

const all = commands();
const groups = new Map();
for (const command of all) {
  const list = groups.get(command.category) ?? [];
  list.push(command);
  groups.set(command.category, list);
}

const lines = [
  '# Command reference',
  '',
  '_Generated by `npm run docs` — do not edit by hand._',
  '',
  'Every command works two ways:',
  '',
  '- **Chat form** — `!command` (the `!` prefix is configurable, and needs Beta APIs enabled).',
  '- **Native form** — `/adm:command`, which autocompletes in the game and works without Beta APIs.',
  '',
  'Arguments in `<angle brackets>` are required; `[square brackets]` are optional.',
  '',
  `There are **${all.length} commands** across ${groups.size} categories.`,
  '',
];

for (const [category, list] of [...groups.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
  lines.push(`## ${category}`, '');
  lines.push('| Command | Permission | Description |');
  lines.push('| --- | --- | --- |');
  for (const command of list.sort((a, b) => a.name.localeCompare(b.name))) {
    const usage = usageOf(command).replace(/\|/g, '\\|');
    const aliases = command.aliases?.length ? ` <br>_aliases: ${command.aliases.map((a) => `\`${a}\``).join(', ')}_` : '';
    const description = command.description.replace(/\|/g, '\\|');
    lines.push(`| \`${usage}\`${aliases} | ${command.permission ? `\`${command.permission}\`` : '—'} | ${description} |`);
  }
  lines.push('');
}

await writeFile(path.join(ROOT, 'docs', 'COMMANDS.md'), lines.join('\n'));
console.log(`docs/COMMANDS.md written (${all.length} commands)`);

const PIPE = '\\|';
const cell = (text) => String(text).replace(/\|/g, PIPE);

/* --------------------------------------------------------- permissions doc */

const permSource = await readFile(path.join(ROOT, 'src', 'core', 'permissions.ts'), 'utf8');

const groupBlock = permSource
  .split('export const PERMISSION_GROUPS: Record<string, string[]> = {')[1]
  .split('\n};')[0];
const permGroups = [...groupBlock.matchAll(/(\w+):\s*\[([\s\S]*?)\]/g)].map(([, name, body]) => [
  name,
  [...body.matchAll(/'([^']+)'/g)].map((m) => m[1]),
]);

const roleMatches = [...permSource.matchAll(
  /\{\s*id: '([^']+)',\s*name: '([^']+)',[\s\S]*?priority: (\d+),([\s\S]*?)\},/g,
)];

const permLines = [
  '# Permissions and roles',
  '',
  '_Generated by `npm run docs` from `src/core/permissions.ts` — do not edit by hand._',
  '',
  '## How checks work',
  '',
  'Permission nodes are dot-separated. A role may hold:',
  '',
  '- an exact node — `players.ban`',
  '- a prefix wildcard — `players.*` matches every `players.` node',
  '- the root wildcard — `*` grants everything',
  '',
  "A player's effective permissions are the union of every role they hold. The",
  'highest-`priority` role supplies their chat prefix and colour.',
  '',
  'Two escape hatches exist:',
  '',
  '- the `admin` tag grants everything, so a fresh world is never locked out',
  '- the `bypass` tag skips land and protection checks',
  '',
  '## Default roles',
  '',
  '| Role | Priority | Grants |',
  '| --- | --- | --- |',
];

for (const [, , name, priority, body] of roleMatches) {
  const permsPart = body.includes('permissions:') ? body.split('permissions:')[1] : '';
  const perms = [...permsPart.matchAll(/'([^']+)'/g)].map((m) => m[1]);
  let shown = perms.slice(0, 6).map((p) => `\`${p}\``).join(', ');
  if (perms.length > 6) shown += ` …(+${perms.length - 6})`;
  const isDefault = body.includes('isDefault: true') ? ' _(default role)_' : '';
  permLines.push(`| **${name}**${isDefault} | ${priority} | ${shown || '—'} |`);
}

const nodeCount = permGroups.reduce((sum, [, nodes]) => sum + nodes.length, 0);
permLines.push('', `## All nodes (${nodeCount})`, '');
for (const [group, nodes] of permGroups) {
  permLines.push(`### ${group}`, '');
  for (const node of nodes) permLines.push(`- \`${node}\``);
  permLines.push('');
}
await writeFile(path.join(ROOT, 'docs', 'PERMISSIONS.md'), permLines.join('\n'));
console.log(`docs/PERMISSIONS.md written (${nodeCount} nodes)`);

/* ------------------------------------------------------- configuration doc */

const cfgSource = await readFile(path.join(ROOT, 'src', 'core', 'config.ts'), 'utf8');
const iface = cfgSource.split('export interface Config {')[1].split('\nexport function defaultConfig')[0];
const defaultsBlock = cfgSource.split('return {')[1].split('\n  };')[0];

const defaults = new Map();
for (const m of defaultsBlock.matchAll(/^ {4}(\w+): (.+?),?$/gm)) defaults.set(m[1], m[2]);

const SECTION_LABELS = new Set(['Economy', 'Teleporting', 'Land claims', 'Presentation', 'Systems', 'Moderation']);

const sections = [];
let current = { title: 'General', rows: [] };
let pending = [];

for (const raw of iface.split('\n')) {
  const line = raw.trim();
  if (line.startsWith('/**') && line.endsWith('*/')) { pending.push(line.slice(3, -2).trim()); continue; }
  if (line.startsWith('/**')) { pending.push(line.slice(3).trim()); continue; }
  if (line.startsWith('*/')) continue;
  if (line.startsWith('*')) { pending.push(line.slice(1).trim()); continue; }

  const field = /^(\w+)\??: ([^;]+);/.exec(line);
  if (field) {
    let note = pending.filter(Boolean).join(' ').trim();
    pending = [];
    const label = note.split('(')[0].trim();
    if (SECTION_LABELS.has(note) || SECTION_LABELS.has(label)) {
      if (current.rows.length) sections.push(current);
      current = { title: note, rows: [] };
      note = '';
    }
    let value = defaults.get(field[1]) ?? '—';
    // Multi-line defaults (arrays) cannot sit in a table cell.
    if (value.startsWith('[') && !value.endsWith(']')) value = '(list, see source)';
    if (value.length > 64) value = value.slice(0, 61) + '…';
    current.rows.push({ name: field[1], type: field[2], value, note });
    continue;
  }
  if (!line && pending.length) {
    const label = pending.join(' ').trim();
    pending = [];
    if (label.length < 48 && !label.endsWith('.')) {
      if (current.rows.length) sections.push(current);
      current = { title: label, rows: [] };
    }
  }
}
if (current.rows.length) sections.push(current);

const TOKENS = [
  ['name', "The player's name"], ['namecolor', 'Their chosen name colour'],
  ['role', 'Highest staff role prefix'], ['rolecolor', 'Highest staff role colour'],
  ['rank', 'Progression rank prefix'], ['rankcolor', 'Progression rank colour'],
  ['rankname', 'Progression rank name'], ['balance', 'Current balance, comma separated'],
  ['symbol', 'Currency symbol'], ['currency', 'Currency name'],
  ['online', 'Players currently online'], ['playtime', 'Total time played'],
  ['kills', 'Player kills'], ['deaths', 'Deaths'], ['mined', 'Blocks mined'],
  ['xp', 'Total XP'], ['clan', 'Clan id, if any'], ['server', 'Configured server name'],
  ['health', 'Current health'], ['maxhealth', 'Maximum health'],
];

const cfgLines = [
  '# Configuration',
  '',
  '_Generated by `npm run docs` from `src/core/config.ts` — do not edit by hand._',
  '',
  'Every setting lives in the world and is edited in-game through',
  '**Admin Suite -> Server Settings**. Nothing needs a file edit or a reload.',
  '',
];
let settingCount = 0;
for (const section of sections) {
  cfgLines.push(`## ${section.title}`, '', '| Setting | Type | Default | Notes |', '| --- | --- | --- | --- |');
  for (const row of section.rows) {
    settingCount++;
    cfgLines.push(`| \`${row.name}\` | \`${cell(row.type)}\` | \`${cell(row.value)}\` | ${cell(row.note)} |`);
  }
  cfgLines.push('');
}
cfgLines.push(
  '## Format tokens',
  '',
  '`chatFormat`, `nametagFormat`, `actionBarFormat`, `sidebarLines`, hologram text',
  'and broadcast messages all expand the same tokens:',
  '',
  '| Token | Value |',
  '| --- | --- |',
  ...TOKENS.map(([token, meaning]) => `| \`{${token}}\` | ${meaning} |`),
  '',
  '`{message}` is additionally available in `chatFormat`.',
  '',
  '> `sidebarLines` may only use server-wide tokens such as `{server}` and',
  "> `{online}`. Bedrock's scoreboard sidebar is a single world-global display,",
  '> so per-player values belong in `actionBarFormat` instead.',
  '',
);
await writeFile(path.join(ROOT, 'docs', 'CONFIGURATION.md'), cfgLines.join('\n'));
console.log(`docs/CONFIGURATION.md written (${settingCount} settings)`);

await rm(outDir, { recursive: true, force: true });
